### ISSUE TITLE
Is it possible to save in a project all the parameters used (colors, shapes and grouping variables)?

### ISSUE THREAD

**Issue by kaizen89** [TissUUmaps/TissUUmapsCore#13]
Hi,
I am loading only csv files with X and Y positions in addition to marker intensities and other variables. It would be nice if one can save all the visualization parameters used for each sample to reload them later on. Is that currently possible?

**Comment by FredrikNysjo** [comment]
Hi!

You can create a button (under "Advanced Settings->Generate button from tab") for each marker tab that you want to include in the exported TMAP-file. That will also save the visualization parameters. You might have to also edit the exported TMAP-file manually, to make sure that the relative path to each CSV is correct (or if you want to change so that a tab should be automatically loaded and displayed when the project is opened).

/Fredrik
