### ISSUE TITLE
Exporting screen capture problem

### ISSUE THREAD

**Issue by npielawski** [TissUUmaps/TissUUmapsCore#14]
When I try to take a screen capture, the paths don't match the size of the image.

Ex:
![kmeans_clustering](https://user-images.githubusercontent.com/11574848/190826951-8d9b7a1f-096c-4891-8732-3e4a06a4a739.png)

I didn't explore this issue further, I just tried the plugin for clustering the points and exported from the menu on TissUUmaps GUI (v3.0.10.1).

**Comment by cavenel** [comment]
Thanks, it's an issue with screens with pixel ratio > 1.
It should be fixed by https://github.com/TissUUmaps/TissUUmaps/commit/2b5964aebd67f328c3947d1ca00a0e86589f341c
It will be part of the next release, but you can also update now using pip:
`pip install https://github.com/TissUUmaps/TissUUmaps/archive/master.zip --no-cache-dir`

**Comment by cavenel** [comment]
This should be fixed in the last release (>=3.0.10.2)
Can you check @npielawski, so that I can close the issue?
