### ISSUE TITLE
Cross-shaped markers are not displayed 

### ISSUE THREAD

**Issue by gapartel** [TissUUmaps/TissUUmapsCore#3]
Hej,

I have noticed that when selecting "Cross" as marker shape, the markers are not displayed. When changing to any other shape they are drawn correctly. I am using Tissuumaps with Google Chrome.

**Comment by cavenel** [comment]
Hi,

I think this issue has been fixed in the develop branch, with this commit: https://github.com/wahlby-lab/TissUUmaps/commit/05dc6158fcc4b7915c42e3598e6aab3cab845615
You can test the develop branch https://github.com/wahlby-lab/TissUUmaps/tree/develop or make the changes from this commit into your TissUUmaps version.
Let me know if it helps!

**Comment by cavenel** [comment]
This should be definitely fixed in 3.0, but feel free to reopen if you still experience the issue.
